### ISSUE TITLE
Fix installer for 1.31

### ISSUE THREAD

**Issue by thenets** [thenets/mediawiki#2]
I don't know why but I got this error after installation:

```
[b5226ffca70b78af6219a183] 2018-06-19 17:32:44: Fatal exception of type "Wikimedia\Rdbms\DBTransactionStateError"
```

Steps to reproduce:
- make build
- make test

**Comment by JoseTomasTocino** [comment]
Yeah me too.

**Comment by thenets** [comment]
@JoseTomasTocino I've created an issue here https://phabricator.wikimedia.org/T197733 but the Wikimedia team doesn't answer :/

I've tried to hack but I couldn't. I don't know how the Mediawiki CLI works.

Try to use the version 1.30 until they fix it.

**Comment by thenets** [comment]
After many months the issue is solved. Version 1.32 fixed everything.
